SET NAMES utf8mb4;

ALTER TABLE `user` DROP INDEX `ft_user_display_name`, DROP INDEX `idx_user_display_name`;
ALTER TABLE `region` DROP INDEX `ft_region_name`;
ALTER TABLE `category` DROP INDEX `ft_category_name`;
ALTER TABLE `rehab_train_guide` DROP INDEX `ft_train_title`;
ALTER TABLE `drug_relief_project` DROP INDEX `ft_donation_search`, DROP INDEX `idx_donation_audit_created`;
ALTER TABLE `help_channel` DROP INDEX `ft_help_channel_name`;
ALTER TABLE `drug_channel` DROP INDEX `ft_drug_channel_name`, DROP INDEX `idx_drug_channel_audit_region`;
ALTER TABLE `disease` DROP INDEX `ft_disease_search`;
ALTER TABLE `examination_manual` DROP INDEX `ft_exam_search`;
ALTER TABLE `relief_project` DROP INDEX `ft_project_search`, DROP INDEX `idx_relief_project_audit_sort`;
ALTER TABLE `article` DROP INDEX `ft_article_search`;
ALTER TABLE `psych_support_org` DROP INDEX `ft_psych_search`;
ALTER TABLE `rehab_institution` DROP INDEX `ft_rehab_inst_search`, DROP INDEX `idx_rehab_audit_region`;
ALTER TABLE `hospital` DROP INDEX `ft_hospital_search`;
ALTER TABLE `doctor` DROP INDEX `ft_doctor_search`, DROP INDEX `idx_doctor_hospital_audit`;
ALTER TABLE `rare_drug` DROP INDEX `ft_drug_names`;
ALTER TABLE `relief_case` DROP INDEX `ft_relief_case_search`, DROP INDEX `idx_relief_case_audit_created_at`, DROP INDEX `idx_relief_case_audit_disease`;
ALTER TABLE `post` DROP INDEX `ft_post_title_content`, DROP INDEX `idx_post_status_created_at`, DROP INDEX `idx_post_status_type_created_at`, DROP INDEX `idx_post_status_like_created_at`;
ALTER TABLE `comment` DROP INDEX `idx_comment_target_tree`, DROP INDEX `idx_comment_root_replies`;
ALTER TABLE `post_like` DROP INDEX `idx_post_like_user_post`;
ALTER TABLE `post_favorite` DROP INDEX `idx_post_favorite_user_post`;
ALTER TABLE `comment_like` DROP INDEX `idx_comment_like_user_comment`;
ALTER TABLE `rehab_institution_disease_rel` DROP INDEX `idx_rehab_disease_institution`;
ALTER TABLE `relief_project_disease_rel` DROP INDEX `idx_project_disease_project`;
